### ISSUE TITLE
Add max_cloud_cover to openEO Sentinel-2 examples

### ISSUE THREAD

**Issue by jdries** [EO-College/cubes-and-clouds#25]
Hi,
just a suggestion, but we try to set a 'max_cloud_cover' in all example code to ensure that users don't forget about this. Even if it is set to 95 (or 99 for that matter), it is very a very useful performance guideline.
This is also explained here:
https://open-eo.github.io/openeo-python-client/data_access.html#filter-on-collection-properties

I'm for instance referring to this notebook, where it seems to be commented out:
https://github.com/EO-College/cubes-and-clouds/blob/main/lectures/3.1_data_processing/exercises/31_data_processing.ipynb

**Comment by przell** [comment]
Hi Jereon, we'll integarte it again to follow best practice! Thanks! ping @Ruphai

**Comment by clausmichele** [comment]
Now it's in the notebook!
