### ISSUE TITLE
Markdown doesn't render correctly

### ISSUE THREAD

**Issue by m-mohr** [EO-College/cubes-and-clouds#27]
In the openEO content there is markdown markup in the text that is non-standard and doesn't render as intended, e.g.

```
::: tip Simplified
<span title="Reducing [mixed greens, cucumber, tomato, onion] returns a salad.">`reduce([🥬, 🥒, 🍅, 🧅], prepare) => 🥗`</span>
:::
```

On openeo.org this renders correctly as it has some extended Markdown functionality, but I think here it should be fixed as the extended Markdown is not available...

Seen in @przell's presentation today ;-)

**Comment by przell** [comment]
Fixed it with this commit: https://github.com/EO-College/cubes-and-clouds/commit/81552043189eccae3aa4be1453491cde17a82d72

@clausmichele, in case you've used it in other places you can adapt accordingly.
