### ISSUE TITLE
intro notebook is_logged_in()

### ISSUE THREAD

**Issue by aljacob** [EO-College/cubes-and-clouds#31]
![image](https://github.com/EO-College/cubes-and-clouds/assets/7644251/3ddf7ec5-17a5-46c1-90d4-6ec81caba6af)
after having successfully logged in I still get an error message when checking if the connection of openEO is correctly logged in.

**Comment by przell** [comment]
I'm aware of that one, we are fixing it at the moment. 
The solution is to use `conn.describe_account()`

**Comment by przell** [comment]
Fixed. @UndeadFairy, can you please updated the exercise also on EOX.
https://github.com/EO-College/cubes-and-clouds/commit/84413d530cd4bde6944738cae7e529f32b0cf3dc
