### ISSUE TITLE
Warnings in exercises 2.3

### ISSUE THREAD

**Issue by przell** [EO-College/cubes-and-clouds#32]
@clausmichele, the notebooks in 2.3 throw some warnings. Just reporting it here. 

![image](https://github.com/EO-College/cubes-and-clouds/assets/51962348/73969eae-38ef-46ce-ad9c-badfb2fc6d7a)

**Comment by Ruphai** [comment]
corresponding packages are now installed in the assigned conda-environment

**Comment by kelewinska** [comment]
Cells [1] and [2] throw a warning due to deprecated `infer_datetime_format`:
![pd_error](https://github.com/EO-College/cubes-and-clouds/assets/20352425/1f465e96-31e0-4fe1-9bdc-7a8e45d95454)
They still run through though.
