### ISSUE TITLE
Improvement exercise 2.3 reduce

### ISSUE THREAD

**Issue by przell** [EO-College/cubes-and-clouds#33]
@clausmichele, 
In the lecture about reducing: https://github.com/EO-College/cubes-and-clouds/blob/main/lectures/2.3_data_access/exercises/23_data_access_reduce.ipynb

- It would be cool to plot the calculated NDVI
- The NDVI values go out of the range -1, 1.
- Calculate the mean or sd on the NDVI (reduce_spatial)
- Plot the timeseries of the values of the mean/sd of the ndvi

**Comment by clausmichele** [comment]
1. Plotting is easy:
![image](https://github.com/EO-College/cubes-and-clouds/assets/31700619/169d1dab-14b5-4347-974c-596f51caa5c5)
2. There seems to be some +-inf derived from NaNs getting into the NDVI formula
3. If we want the number, it means that it will download the whole set of data. Doable, but I'd rather reduce the time range or the spatial AOI to reduce the downloaded data
4. Same as before. Better to reduce the AOI and increase the time range?

**Comment by przell** [comment]
1. Plotting is fine!
2. There have also been some other values like 2.43 for example
3. Can we not reduce all the time steps to one number, the mean, and then plot that as a time series. The download should then only be one value per time step? ...
4. ... then just plot this time series.

**Comment by clausmichele** [comment]
2. I will investigate
3. To aggregate the values you firstly need them! And since we're computing locally, it would anyway have to download data first.

**Comment by przell** [comment]
3. Yeah, forgot about the local computation part. Either we reduce the AOI drastically, or we just don't show a time series. Up to you ;)

**Comment by clausmichele** [comment]
Solved in the last commit!
