### ISSUE TITLE
Improvement exercise 2.3 resample 

### ISSUE THREAD

**Issue by przell** [EO-College/cubes-and-clouds#34]
@clausmichele, 
the resample exercise ends abruptly. It doesn't seem finished at that point.
https://github.com/EO-College/cubes-and-clouds/blob/main/lectures/2.3_data_access/exercises/23_data_access_resample.ipynb

**Comment by clausmichele** [comment]
True, I think that my plan was to implement `resample_cube_temporal`, which is missing (see here https://github.com/Open-EO/openeo-processes-dask/issues/175). Probably it's better to remove the last part and keep spatial resampling only.

**Comment by przell** [comment]
Jup, just remove it!

**Comment by clausmichele** [comment]
The issue with NDVI values out of scale is related to this https://github.com/Element84/earth-search/issues/23

**Comment by clausmichele** [comment]
Solved in the last commit!
