### ISSUE TITLE
Improvement exercise 3.2 validation

### ISSUE THREAD

**Issue by clausmichele** [EO-College/cubes-and-clouds#35]
The exercise https://github.com/EO-College/cubes-and-clouds/blob/main/lectures/3.2_validation/3.2_exercises/32_validation.ipynb is using the [32_cubes_utilities.py](https://github.com/EO-College/cubes-and-clouds/blob/main/lectures/3.2_validation/3.2_exercises/32_cubes_utilities.py) file.

To import the functions defined inside, there's a call to `%run 32_cubes_utilities.py`.

It would be better to rename the file to either `_32_cubes_utilities.py` or `cubes_utilities_32.py`, so that the filename doesn't start with a number and we can import the functions with:

```python
from _32_cubes_utilities import *`
```
or better import only the used functions:

```python
from _32_cubes_utilities import visualize_bbox, generate_stac
```

**Comment by Ruphai** [comment]
thank you @clausmichele for pointing this out. The exercise has been updated accordingly to import only the used functions.
