### ISSUE TITLE
Embed S2 Tile Calculator in md

### ISSUE THREAD

**Issue by przell** [EO-College/cubes-and-clouds#36]
@jonas-eberle, can we embed the S2 Tile Calculator also here?

https://github.com/EO-College/cubes-and-clouds/blob/main/lectures/1.1_intro_platform/1.1_intro_platform.md#animated-content-data-volume-calculator-java-application

**Comment by clausmichele** [comment]
This was implemented with this commit https://github.com/EO-College/cubes-and-clouds/commit/8e0aff5426d6749dd3960298dbb453b72a627337, I close the issue.
