### ISSUE TITLE
Unified Python Kernel for running MOOC Exercise

### ISSUE THREAD

**Issue by Ruphai** [EO-College/cubes-and-clouds#41]
**Context**: The Suite of Exercises in the MOOC should be able to run with one unified kernel containing all necessary packages and dependencies. In the ESA MOOC called Cubes-and-Clouds, but currently we have two python kernels running, with each respective kernels failing on different exercises. 

**Issue:** The `Cubes-and-Clouds2` kernel currently has a version of leaflet with an `ipyleaflet` backend that contains the `draw_features` method, which allows for the interactivity in the Data Sharing Exercise. However, the `Cubes-and-Cloud` Kernel has an version of leaflet with the `folium` backend installed and works well for all the other exercises, except for the Data Sharing one. The target would be to have a unified python kernel that works for all the exercises. 

**Potential solution:** Include the interactive function of `ipyleaflet` as a utility function and use kernel containing Folium to run all the other exercises.

**Comment by Ruphai** [comment]
This is also related to: [#37](https://github.com/EO-College/cubes-and-clouds/issues/37#issue-2188001873)

**Comment by clausmichele** [comment]
We don't plan to unify the kernels, since they are automatically selected based on the exercise notebook.
