### ISSUE TITLE
Adding Github action & Jupyter-book to render nb

### ISSUE THREAD

**Issue by annefou** [EO-College/cubes-and-clouds#43]
The idea is to add a GitHub action to render the course (markdown and Jupyter notebooks) on Github webpages.

I made it in my fork: https://github.com/annefou/cubes-and-clouds/tree/main/.github/workflows

and the rendered Jupyter book is available online. For now in https://annefou.github.io/cubes-and-clouds

I suggest to add the same in the parent repo so anyone can read the course online, including Jupyter notebooks.

**Comment by clausmichele** [comment]
Hi @annefou, it looks great! Could you create a PR so that we can add it to the main repo?

**Comment by annefou** [comment]
It is done and I suggest we add some info and the link to the rendered Jupyter book version in [CONTRIBUTING](https://github.com/EO-College/cubes-and-clouds/blob/main/CONTRIBUTING.md). The idea is to make it easier to check the rendered version from GitHub. Also we will add how to build the Jupyter book locally to help contributors to check their changes.

What do you think?

**Comment by clausmichele** [comment]
@annefou fine, can you or @tinaok add those additional info?
