### ISSUE TITLE
Introduce Pangeo in the MOOC 

### ISSUE THREAD

**Issue by annefou** [EO-College/cubes-and-clouds#47]
We need to introduce Pangeo in the MOOC for instance when introducing the different EO platform.

For now I added Pangeo in the list of cloud-based EO platform providers.

See https://github.com/annefou/cubes-and-clouds/blob/platform/lectures/1.1_intro_platform/1.1_intro_platform.md

Your feedback is welcome.

**Comment by clausmichele** [comment]
Hi @annefou, maybe it would be worth to mention that the physical infrastructure where a Pangeo "platform" is currently running is the EOSC?
Reading through the content, it's incredible how the information we collected is already partly outdated: Microsoft Planetary Computer does not offer computing capabilities anymore...

**Comment by clausmichele** [comment]
@annefou please create a PR for this so that I can merge it.
