### ISSUE TITLE
1.3_open_science: video on gdal [test issue]

### ISSUE THREAD

**Issue by przell** [EO-College/cubes-and-clouds#7]
@edzer, hi, would you be interested in participating in a short video for the open science lecture that explains how/why GDAL is open source and the role/impact of GDAL has in geo/EO and how it's constantly evolving. The section in the preliminary script of the lecture where this video would come in is here: https://github.com/EO-College/cubes-and-clouds/blob/main/lectures/1.3_openscience/1.3_openscience.md#gdal---geographic-data-abstraction-library

**Note:** *This is a test issue. I wanted to check whether it's a good workflow to have external experts collaborate here on the github repo. If you feel something is missing in the script or you have any comments feel free to either open an issue or a pull request on this lecture: https://github.com/EO-College/cubes-and-clouds/blob/main/lectures/1.3_openscience/1.3_openscience.md*

**Comment by edzer** [comment]
Sure, happy to do so!

**Comment by przell** [comment]
@edzer, thanks for the quick and positive reply! We'll get back to you with more details once we have advanced a bit more with the content creation.

**Comment by przell** [comment]
@edzer, I have drafted most of the open science lecture now. Would you agree to have a look at it? I think the general part is quite done (up to section "open science journey"). https://github.com/EO-College/cubes-and-clouds/blob/main/lectures/1.3_openscience/1.3_openscience.md

Where you're contribution would be valuable is: The role of open science in (cloudnative) geospatial/EO.
I have drafted some ideas here https://github.com/EO-College/cubes-and-clouds/blob/main/lectures/1.3_openscience/1.3_openscience.md#examples-of-open-science-in-eo and here https://github.com/EO-College/cubes-and-clouds/blob/main/lectures/1.3_openscience/1.3_openscience.md#examples-of-open-science-in-eo

I could imagine a video of about 3 to 5 minutes .  That showcases the importance of open science in geospatial, the transition to cloud, and motivates the listeners to use and contribute to these projects (even if only with reporting issues).
The next steps would be to agree on the exact aim of the video, the topics, and structure. In example, structure the bullet points in the .md document for a script.
